[bundles]


[versions]
agp = "8.13.1"
coreKtx = "1.17.0"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.9.4"
activityCompose = "1.11.0"
uiGraphicsAndroid = "1.5.1"
material3Android = "1.2.0"
runtimeAndroid = "1.5.1"
javaxInject = "1"
kotlinxCoroutines = "1.8.1"

# Timber
timber = "5.0.1"

## Compose
# https://developer.android.com/develop/ui/compose/bom/bom-mapping
androidxComposeBom = "2025.01.01"
# https://developer.android.com/jetpack/androidx/releases/navigation
androidxComposeNavigation = "2.8.6"
# https://developer.android.com/jetpack/androidx/releases/compose-material3
androidxComposeMaterial3 = "1.3.1"

## Network
# okhttp
# # https://square.github.io/okhttp/
okhttp = "4.12.0"
# Retrofit
# # https://github.com/square/retrofit
retrofit = "2.11.0"

## Kotlin
# https://github.com/JetBrains/kotlin
kotlin = "2.0.0"
ksp = "2.0.0-1.0.24"   # Kotlin 2.0 호환 KSP 버전
composeCompiler = "1.5.15"  # Compose Compiler (2.0과 호환)
# https://github.com/Kotlin/kotlinx.serialization
kotlinxSerializationJson = "1.8.0"
# https://github.com/Kotlin/kotlinx-datetime/releases
kotlinxDatetime = "0.6.1"
# https://github.com/Kotlin/kotlinx.collections.immutable
kotlinxImmutable = "0.3.8"

## Hilt
# https://github.com/google/dagger/releases
hilt = "2.55"
# https://developer.android.com/jetpack/androidx/releases/hilt
hiltNavigationCompose = "1.2.0"

# https://github.com/detekt/detekt
detekt = "1.23.7"
junit = "4.13.2"
appcompat = "1.7.1"
material = "1.13.0"
core = "1.8.0"
roomKtx = "2.8.3"

coil = "2.5.0"
accompanist = "0.30.1"
foundation = "1.9.5"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidxComposeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-ui-graphics-android = { group = "androidx.compose.ui", name = "ui-graphics-android", version.ref = "uiGraphicsAndroid" }
androidx-material3-android = { group = "androidx.compose.material3", name = "material3-android", version.ref = "material3Android" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "androidxComposeMaterial3" }
androidx-runtime-android = { group = "androidx.compose.runtime", name = "runtime-android", version.ref = "runtimeAndroid" }

okhttp-logging = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
retrofit-core = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-kotlin-serialization = { module = "com.squareup.retrofit2:converter-kotlinx-serialization", version.ref = "retrofit" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
javax-inject = { group = "javax.inject", name = "javax.inject", version.ref = "javaxInject" }

hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }

android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
compose-compiler-gradle-plugin = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }
hilt-android-gradle-plugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }


# Gradle Plugin dependencies (build-logic에서 compileOnly로 사용)
compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "composeCompiler" }
ksp = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }

# plugin
verify-detektPlugin = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junit" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-core = { group = "androidx.core", name = "core", version.ref = "core" }

# coroutines
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }

# timber
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }

# navigation
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version = "2.8.6" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavigationCompose" }

retrofit-bom = { module = "com.squareup.retrofit2:retrofit-bom", version.ref = "retrofit" }

kotlinx-immutable = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "kotlinxImmutable" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "roomKtx" }

coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
accompanist-pager = { module = "com.google.accompanist:accompanist-pager", version.ref = "accompanist" }
accompanist-pager-indicators = { module = "com.google.accompanist:accompanist-pager-indicators", version.ref = "accompanist" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "foundation" }

[plugins]
kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }


## precompiled plugins
example-android-application = { id = "example.android.application", version = "unspecified" }
example-android-library = { id = "example.android.library", version = "unspecified" }
example-core = { id = "example.core", version = "unspecified" }
example-feature = { id = "example.feature", version = "unspecified" }
